### PR TITLE
features/eu-debug: Remove kunit changes

### PR DESCRIPTION
**Pull request by kolanupa**
Adding the missing kunit related patches without which build is getting
fail on kunit config enablement.

Signed-off-by: Kolanupaka Naveena <kolanupaka.naveena@intel.com>

### CODE REVIEW

**Review by ayazahma — CHANGES_REQUESTED** [review]
pls update script to have eu debug tree  by default also update the Readme for script changees

**Review by ayazahma — APPROVED** [review]

**Comment by lucasdemarchi** [comment]
there are regressions showing up in CI when you take the features in. Also, why would it be used by default? Hopefully we are not trying to send to Ubuntu by mistake on the generic kernel.

**Comment by kolanupa** [comment]
> there are regressions showing up in CI when you take the features in. Also, why would it be used by default? Hopefully we are not trying to send to Ubuntu by mistake on the generic kernel.

Core BAT results are good,
Regression seen only on display tests especially for kms_psr* tests. Looks like all tests got passed but seen dmesg warn/crash in the logs. Hence the percentage got dropped. We will ask display team to have a look.

**Comment by ayazahma** [comment]
we have clearly informed Ubuntu that Patches in base folder need to taken in generic-kernel and patches in features folder are for linux-intel kernel

**Pull request merged**
